name: acne-sense

services:
  acne-sense-api:
    image: acne-sense-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - FLASK_PORT=${FLASK_PORT:-5000}
    ports:
      - "${FLASK_PORT:-5000}:${FLASK_PORT:-5000}"
    volumes:
      - ./api/data:/app/data
      - ./api/models:/app/models
    env_file:
      - ./api/.env
    networks:
      - acne-sense-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FLASK_PORT:-5000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  acne-sense-web:
    image: acne-sense-web:latest
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env
    networks:
      - acne-sense-network
    restart: unless-stopped
    depends_on:
      - acne-sense-api

networks:
  acne-sense-network:
    driver: bridge