name: Deploy Web App to Cloud Run

env:
  SERVICE_NAME: acne-sense-web
  PROJECT_ID: acne-sense
  REGION: asia-southeast1
  DOCKER_IMAGE_URL: asia-southeast1-docker.pkg.dev/acne-sense/acne-sense-web/acne-sense-web
  
  # Common environment variables for all deployments
  COMMON_ENV_VARS: >-
    NODE_ENV=production
  
  # Environment-specific API URLs
  PROD_API_URL: https://acne-sense-api-143761779858.asia-southeast1.run.app
  STAGING_API_URL: https://acne-sense-api-staging-143761779858.asia-southeast1.run.app
  WEB_STAGING_API_URL: https://acne-sense-api-api-staging-143761779858.asia-southeast1.run.app

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
  pull_request:
    branches:
      - main
    paths:
      - 'web/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - web-staging
          - production

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set deployment variables
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Manual deployment
            case "${{ github.event.inputs.environment }}" in
              "staging")
                echo "SERVICE_SUFFIX=-staging" >> $GITHUB_ENV
                echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
                ;;
              "web-staging")
                echo "SERVICE_SUFFIX=-web-staging" >> $GITHUB_ENV
                echo "DEPLOY_ENV=web-staging" >> $GITHUB_ENV
                ;;
              "production")
                echo "SERVICE_SUFFIX=" >> $GITHUB_ENV
                echo "DEPLOY_ENV=production" >> $GITHUB_ENV
                ;;
            esac
          elif [[ "${{ github.ref }}" == "refs/heads/main" && "${{ github.event_name }}" == "push" ]]; then
            # Auto deployment to production
            echo "SERVICE_SUFFIX=" >> $GITHUB_ENV
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # PR preview
            echo "SERVICE_SUFFIX=-pr-${{ github.event.number }}" >> $GITHUB_ENV
            echo "DEPLOY_ENV=pr-preview" >> $GITHUB_ENV
          fi

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          # Use branch name or environment as tag for staging deployments
          if [[ "${{ env.DEPLOY_ENV }}" == "staging" || "${{ env.DEPLOY_ENV }}" == "web-staging" ]]; then
            TAG="${{ env.DEPLOY_ENV }}-${{ github.sha }}"
          else
            TAG="${{ github.sha }}"
          fi
          
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:${TAG} -f Dockerfile .
          docker push ${{ env.DOCKER_IMAGE_URL }}:${TAG}
          
          # Also tag as latest for the specific environment
          if [[ "${{ env.DEPLOY_ENV }}" == "staging" ]]; then
            docker tag ${{ env.DOCKER_IMAGE_URL }}:${TAG} ${{ env.DOCKER_IMAGE_URL }}:staging-latest
            docker push ${{ env.DOCKER_IMAGE_URL }}:staging-latest
          elif [[ "${{ env.DEPLOY_ENV }}" == "web-staging" ]]; then
            docker tag ${{ env.DOCKER_IMAGE_URL }}:${TAG} ${{ env.DOCKER_IMAGE_URL }}:web-staging-latest
            docker push ${{ env.DOCKER_IMAGE_URL }}:web-staging-latest
          elif [[ "${{ env.DEPLOY_ENV }}" == "production" ]]; then
            docker tag ${{ env.DOCKER_IMAGE_URL }}:${TAG} ${{ env.DOCKER_IMAGE_URL }}:latest
            docker push ${{ env.DOCKER_IMAGE_URL }}:latest
          fi

      - name: Set environment variables
        run: |
          # Set environment-specific variables
          if [[ "${{ env.DEPLOY_ENV }}" == "staging" ]]; then
            ENV_VARS="${{ env.COMMON_ENV_VARS }},API_BASE_URL=${{ env.STAGING_API_URL }}"
          elif [[ "${{ env.DEPLOY_ENV }}" == "web-staging" ]]; then
            ENV_VARS="${{ env.COMMON_ENV_VARS }},API_BASE_URL=${{ env.WEB_STAGING_API_URL }}"
          else
            ENV_VARS="${{ env.COMMON_ENV_VARS }},API_BASE_URL=${{ env.PROD_API_URL }}"
          fi
          
          echo "DEPLOYMENT_ENV_VARS=${ENV_VARS}" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          # Remove whitespace from ENV_VARS
          ENV_VARS=$(echo "${{ env.DEPLOYMENT_ENV_VARS }}" | tr -d ' \n\t')
          
          # Set image tag
          if [[ "${{ env.DEPLOY_ENV }}" == "staging" || "${{ env.DEPLOY_ENV }}" == "web-staging" ]]; then
            IMAGE_TAG="${{ env.DEPLOY_ENV }}-${{ github.sha }}"
          else
            IMAGE_TAG="${{ github.sha }}"
          fi
          
          # Deploy with appropriate service name
          SERVICE_NAME="${{ env.SERVICE_NAME }}${{ env.SERVICE_SUFFIX }}"
          
          gcloud run deploy ${SERVICE_NAME} \
            --image ${{ env.DOCKER_IMAGE_URL }}:${IMAGE_TAG} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --memory 1Gi \
            --cpu 1 \
            --port 3000 \
            --set-env-vars="${ENV_VARS}" \
            --update-secrets="SUPABASE_URL=acne-sense-supabase-url:latest,SUPABASE_KEY=acne-sense-supabase-key:latest,SUPABASE_SERVICE_ROLE_KEY=acne-sense-supabase-service-role-key:latest,JWT_SECRET=acne-sense-jwt-secret:latest,SUPABASE_PG_CONNECTION_STRING=acne-sense-supabase-pg-connection-string:latest" \
            --service-account acne-sense-sa@acne-sense.iam.gserviceaccount.com \
            $( [[ "${{ github.event_name }}" == "pull_request" ]] && echo "--tag pr-${{ github.event.number }}" || echo "" )

      - name: Output deployment info
        run: |
          SERVICE_NAME="${{ env.SERVICE_NAME }}${{ env.SERVICE_SUFFIX }}"
          echo "🚀 Deployed to: ${SERVICE_NAME}"
          echo "Environment: ${{ env.DEPLOY_ENV }}"
          echo "Region: ${{ env.REGION }}"
          
          # Get service URL
          SERVICE_URL=$(gcloud run services describe ${SERVICE_NAME} \
            --region=${{ env.REGION }} \
            --format="value(status.url)")
          echo "URL: ${SERVICE_URL}"

      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: service } = await google.run('v1').projects.locations.services.get({
              name: `projects/${{ env.PROJECT_ID }}/locations/${{ env.REGION }}/services/${{ env.SERVICE_NAME }}-pr-${{ github.event.number }}`
            });
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Web App Preview deployment ready!**\n\nURL: ${service.status.url}\n\nThis preview will be available until the PR is merged or closed.`
            });
