name: acne-sense-api

services:
  acne-sense-api:
    image: acne-sense-gemini:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FLASK_PORT=${FLASK_PORT}
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - acne-sense-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FLASK_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  acne-sense-network:
    driver: bridge