version: '3.8'

services:
  acne-sense-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acne-sense-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
      - OLLAMA_API_URL=http://ollama:11434/api/generate
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - DEFAULT_MODEL=qwen2:7b
    volumes:
      - ./data:/app/data
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - acne-sense-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - acne-sense-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  acne-sense-network:
    driver: bridge

volumes:
  ollama-data:
    driver: local