services:
  acne-sense-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acne-sense-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
      - VLLM_API_URL=http://vllm-service:8080/v1/completions
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - DEFAULT_MODEL=Qwen/Qwen2.5-7B-Instruct
    volumes:
      - ./data:/app/data
    depends_on:
      - vllm-service
    networks:
      - acne-sense-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  vllm-service:
    image: vllm/vllm-openai
    container_name: vllm-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./models:/models:ro  #
    command: >
      --model /models/Qwen2.5-3B-Instruct-AWQ
    networks:
      - acne-sense-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  acne-sense-network:
    driver: bridge

volumes:
  vllm-models:
    driver: local